# Site settings
title: Lambdaspace
email: participation@mozilla.com
description: >
    Get involved with the lambdaspace
baseurl: ""
url: "https://lambdaspace.gr"
twitter_username: lambdaspace
github_username:  lambdaspace

# Build settings
markdown: kramdown

include: ['_pages']
